name: Pull Request
run-name: Validate Pull Request
on: [pull_request]
jobs:
    duplicate-code:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0
            - uses: astubbs/duplicate-code-cross-check@v1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  directories: src
                  cpd-min-tokens: '35'
                  cpd-max-duplication: '5'
                  jscpd-min-lines: '2'
                  jscpd-min-tokens: '35'
                  jscpd-max-duplication: '5'
    pmd_job:
        runs-on: ubuntu-latest
        name: PMD job with cache
        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            - name: Run PMD
              uses: kemsakurai/action-pmd@aafc862a11dd31e0f93c8c4d06e403fd6bbcca8b
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  reporter: 'github-pr-review'
                  tool_name: 'pmd_reviewdog'
                  pmd_cache: '/tmp/pmd-cache/pmd.cache'
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v6
            - name: validate gradle wrapper
              uses: gradle/actions/wrapper-validation@v6
            - name: setup jdk
              uses: actions/setup-java@v5
              with:
                  java-version: '25'
                  distribution: 'microsoft'
            - name: make gradle wrapper executable
              run: chmod +x ./gradlew
            - name: build
              run: ./gradlew build
            - name: capture build artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: Artifacts
                  path: |
                      build/libs/*.jar
                      !build/libs/*-sources.jar
