name: Pull Request
run-name: Validate Pull Request
on: [pull_request]
jobs:
    duplicate-code:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0
            - uses: astubbs/duplicate-code-cross-check@v1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  directories: src
                  cpd-min-tokens: '35'
                  cpd-max-duplication: '5'
                  jscpd-min-lines: '2'
                  jscpd-min-tokens: '35'
                  jscpd-max-duplication: '5'
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v6
            - name: validate gradle wrapper
              uses: gradle/actions/wrapper-validation@v6
            - name: setup jdk
              uses: actions/setup-java@v5
              with:
                  java-version: '25'
                  distribution: 'microsoft'
            - name: make gradle wrapper executable
              run: chmod +x ./gradlew
            - name: build
              run: ./gradlew build
            - name: capture build artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: Artifacts
                  path: |
                      build/libs/*.jar
                      !build/libs/*-sources.jar
