name: Pull Request
run-name: Validate Pull Request
on: [pull_request]
jobs:
    duplicate-code:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0
            - uses: astubbs/duplicate-code-cross-check@v1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  directories: src
                  cpd-min-tokens: '35'
                  cpd-max-duplication: '5'
                  jscpd-min-lines: '2'
                  jscpd-min-tokens: '35'
                  jscpd-max-duplication: '5'
    pmd-analyser-check:
        name: PMD Static Code Analysis
        permissions:
            security-events: write
            actions: read
            contents: read
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                  # Incremental diffs require fetch depth to be at 0 to grab the target branch
                  fetch-depth: '0'
            - name: Run Full PMD Analysis
              if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
              id: pmd-full-analysis
              uses: synergy-au/pmd-analyser-action@v2.1
              with:
                  analyse-all-code: 'true'
                  pmd-version: 'latest'
                  file-path: './src'
                  rules-path: './pmd-ruleset.xml'
                  error-rules: 'AvoidDirectAccessTriggerMap,AvoidDmlStatementsInLoops,AvoidHardcodingId'
                  note-rules: 'ApexDoc'
            - name: Run PMD Analysis on Files Changed
              id: pmd-partial-analysis
              if: github.event.pull_request != null
              uses: synergy-au/pmd-analyser-action@v2.1
              with:
                  pmd-version: 'latest'
                  file-path: './src'
                  rules-path: './pmd-ruleset.xml'
                  error-rules: 'AvoidDirectAccessTriggerMap,AvoidDmlStatementsInLoops,AvoidHardcodingId'
                  note-rules: 'ApexDoc'
            - name: Upload results to GitHub
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: pmd-output.sarif
            - name: No PMD Errors?
              run: |
                  if ${{ steps.pmd-full-analysis.outputs.error-found }} ${{ steps.pmd-partial-analysis.outputs.error-found }}
                  then
                    exit 3
                  fi
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v6
            - name: validate gradle wrapper
              uses: gradle/actions/wrapper-validation@v6
            - name: setup jdk
              uses: actions/setup-java@v5
              with:
                  java-version: '25'
                  distribution: 'microsoft'
            - name: make gradle wrapper executable
              run: chmod +x ./gradlew
            - name: build
              run: ./gradlew build
            - name: capture build artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: Artifacts
                  path: |
                      build/libs/*.jar
                      !build/libs/*-sources.jar
